name: ChunkyPause
version: 1.1.0
main: org.popcraft.chunkypause.ChunkyPause
api-version: 1.21.8
depend: [ Chunky ]
authors: [ pop4959, Paulem , AlexAn75541]
description: Additional pause functionality for Chunky
commands:
  chunkypause:
    description: Set the player count to pause at.
    permission: chunkypause
permissions:
  chunkypause:
    default: op
